---
kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: kibana-httpproxy
  namespace: elastic-system
spec:
  routes:
    - services:
        - name: kibana-kb-http
          port: 5601
