apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ephemeral-roles
  namespace: monitoring
spec:
  endpoints:
  - port: http
  namespaceSelector:
    matchNames:
    - ephemeral-roles
  selector:
    matchLabels:
      app: ephemeral-roles
