{
 "title": "Ephemeral Roles Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Uptime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "content": "<br/>\n<center>\n  <a href=\"https://github.com/ewohltman/ephemeral-roles\"><img src=\"https://github.com/ewohltman/ephemeral-roles/raw/master/web/static/Testa_Anatomica-Filippo_Balbi.jpg\" width=\"50\"></a>\n  &nbsp\n  <a href=\"https://github.com/ewohltman/ephemeral-roles\">ephemeral-roles</a>\n</center>"
  },
  {
   "title": "Bot Uptime",
   "type": "graph",
   "gridPos": { "h": 3, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "avg(label_replace(up{namespace=\"ephemeral-roles\",service=\"ephemeral-roles\"}, \"instance\", \"\", \"instance\", \".+\"))",
     "legendFormat": "uptime"
    }
   ]
  },
  { "title": "Usage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Bot Servers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(ephemeral_roles_guilds_count, \"instance\", \"\", \"instance\", \".+\"))",
     "legendFormat": "servers"
    }
   ]
  },
  {
   "title": "Bot Server Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "label_replace(ephemeral_roles_guilds_count{pod=~\"ephemeral-roles-.+\"}, \"instance\", \"\", \"instance\", \".+\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bot Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(ephemeral_roles_members_count, \"instance\", \"\", \"instance\", \".+\"))",
     "legendFormat": "users"
    }
   ]
  },
  {
   "title": "Bot Users Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "label_replace(ephemeral_roles_members_count{pod=~\"ephemeral-roles-.+\"}, \"instance\", \"\", \"instance\", \".+\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Discord Event Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "VoiceStateUpdate - Events Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(irate(ephemeral_roles_voice_state_update_events[1m]), \"instance\", \"\", \"instance\", \".+\"))",
     "legendFormat": "events/second"
    }
   ]
  },
  {
   "title": "MessageCreate - Events Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(irate(ephemeral_roles_message_create_events[1m]), \"instance\", \"\", \"instance\", \".+\"))",
     "legendFormat": "events/second"
    }
   ]
  },
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "RES Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "label_replace(process_resident_memory_bytes{pod=~\"ephemeral-roles.+\"}, \"instance\", \"\", \"instance\", \".+\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(go_memstats_heap_objects{pod=~\"ephemeral-roles-.+\"}, \"instance\", \"\", \"instance\", \".+\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(process_cpu_seconds_total{pod=~\"ephemeral-roles-.+\"}[1m]), \"instance\", \"\", \"instance\", \".+\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(go_goroutines{pod=~\"ephemeral-roles-.+\"}, \"instance\", \"\", \"instance\", \".+\")",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}