---
kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: argocd-httpproxy
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: argocd.ephemeral-roles.net
  includes:
    - name: argocd-httpproxy
      namespace: argocd

