kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  name: kibana-httpproxy
  namespace: projectcontour
spec:
  virtualhost:
    fqdn: kibana.ephemeral-roles.net
  includes:
    - name: kibana-httpproxy
      namespace: logging
