apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogMW0KcmVjZWl2ZXJzOgogIC0gbmFtZTogZGVmYXVsdC1yZWNlaXZlcgogIC0gbmFtZTogcG9kLWJvdW5jZXIKICAgIHdlYmhvb2tfY29uZmlnczoKICAgICAgLSB1cmw6IGh0dHA6Ly9wb2QtYm91bmNlci5lcGhlbWVyYWwtcm9sZXMuc3ZjLmNsdXN0ZXIubG9jYWw6ODA4MC9hbGVydApyb3V0ZToKICBncm91cF9ieTogWydhbGVydG5hbWUnXQogIGdyb3VwX3dhaXQ6IDMwcwogIGdyb3VwX2ludGVydmFsOiA1bQogIHJlcGVhdF9pbnRlcnZhbDogMTVtCiAgcmVjZWl2ZXI6IGRlZmF1bHQtcmVjZWl2ZXIKICByb3V0ZXM6CiAgICAtIG1hdGNoX3JlOgogICAgICAgIGFsZXJ0bmFtZTogRXBoZW1lcmFsUm9sZXMtR29yb3V0aW5lcwogICAgICByZWNlaXZlcjogcG9kLWJvdW5jZXIK
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
