apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.23.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m
    receivers:
      - name: default-receiver
      - name: pod-bouncer
        webhook_configs:
          - url: http://pod-bouncer.ephemeral-roles.svc.cluster.local:8080/alert
    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 15m
      receiver: default-receiver
      routes:
        - match_re:
          alertname: EphemeralRoles-Goroutines
          receiver: pod-bouncer
type: Opaque
